### ISSUE TITLE
OC 0.6.3?

### ISSUE THREAD

**Issue by perteraul** [tagyro/Hackintosh_Gigabyte_Z490_Aorus_Ultra#1]
Hi! Thanks for your EFI — I mainly have the same setup, plus the i9-10900K. Did you manage to turn of the motherboard's Bluetooth? I too tried with the boot argument HS14, but that's not working...

Oh, also, did you update to OC 0.6.3? Thanks!

**Comment by perteraul** [comment]
Ok, so I found a solution to disable the onboard Bluetooth. 

I used Hackintool to see all the available ports — and deleted the HS14 one from the list, then used the Export button to create a `USBPorts.kext` file. Went on and added that file to the EFI/OC/Kexts and opened config.plist with ProperTree and applied an OC Snapshot on it. Restarted the hack and Bluetooth worked instantly. 

I'll probably create a repository with my EFI as well, including OC 0.6.3, but only after I test everything with Big Sur GM. 

Cc: @tagyro 

Also - hi buddy!

**Comment by tester89** [comment]
> Ok, so I found a solution to disable the onboard Bluetooth.
> 
> I used Hackintool to see all the available ports — and deleted the HS14 one from the list, then used the Export button to create a `USBPorts.kext` file. Went on and added that file to the EFI/OC/Kexts and opened config.plist with ProperTree and applied an OC Snapshot on it. Restarted the hack and Bluetooth worked instantly.
> 
> I'll probably create a repository with my EFI as well, including OC 0.6.3, but only after I test everything with Big Sur GM.
> 
> Cc: @tagyro
> 
> Also - hi buddy!

Hi, were you able to update this to OpceCore 0.6.3 or even to 0.6.4? I have same specs, will really appreciate if you could share EFI folder.

**Comment by tagyro** [comment]
I haven't had a chance to update to 0.6.3/4 yet - will probably try over the holiday but I have no issues with 0.6.2 and I also don't plan on updating to Big Sur anytime soon.
Maybe @perteraul?

**Comment by perteraul** [comment]
@tester89 I have created a repository for my build (Z490 Aorus Ultra, i9 10900K, 5700XT) using the latest OpenCore version and have included the EFI. You can find it [here](https://github.com/perteraul/HackPro).
