### ISSUE TITLE
Can you please post updated version?

### ISSUE THREAD

**Issue by tester89** [tagyro/Hackintosh_Gigabyte_Z490_Aorus_Ultra#2]
Hi, I have same board and processor. Can you please post EFI for this hackintosh. I will really appreciate.  Thanks,

**Comment by tagyro** [comment]
I made a [v1.0 release](https://github.com/tagyro/Hackintosh_Gigabyte_Z490_Aorus_Ultra/releases/tag/1.0) for easier download but you still need to generate your own UUID with [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS) and add it in the `config.plist`
