### ISSUE TITLE
Boot loops

### ISSUE THREAD

**Issue by tester89** [tagyro/Hackintosh_Gigabyte_Z490_Aorus_Ultra#3]
I have same motherboard and processor.

After adding your EFI and choosing Macintosh it just reboots again.

**Comment by tagyro** [comment]
Have you modified the `config.plist` to edit the SMUUID like per the README?
Did you add all the required kext's?
My EFI is in debug mode - are you able to see any error on the screen while loading?

**Comment by tester89** [comment]
> Have you modified the `config.plist` to edit the SMUUID like per the README?
> Did you add all the required kext's?
> My EFI is in debug mode - are you able to see any error on the screen while loading?

Hi, i fixed the boot loop issue, But my Bluetooth in fenvi card is not working. Wifi works but Bluetooth doesn't.

**Comment by tagyro** [comment]
You most probably need to disable the onboard wifi/bluetooth - I'll update the USB SSDT in the main repo.
(you have to disable usb 14 with hackintool)

**Comment by tagyro** [comment]
I don't have the machine anymore, I'll check if I have a copy of the EFI folder somewhere.

**Be sure to do a backup of any existing files and the config.plist before anything**

The basic is: using [Hackintool](https://github.com/headkaze/Hackintool), in the USB pane, disable USB 14 and export the configuration and move the .aml files in your EFI partition (in the correct folder!).
Open the _config.plist_ with [ProperTree](https://github.com/corpnewt/ProperTree) and link the new files (CMD-R in ProperTree and select the OC folder).
Save config.plist, cross fingers and reboot.
If all goes well, the Intel Wifi should be disabled and have native support for the wifi and bluetooth.
If not, re-open Hackintool and check if USB 14 is really disabled. Also, maybe double check that it's Intel and 14 Mbps (at least for bluetooth).
Good luck!
