### ISSUE TITLE
Won’t be able to boot to USB

### ISSUE THREAD

**Issue by goldenbilla** [tagyro/Hackintosh_Gigabyte_Z490_Aorus_Ultra#4]
Hi i created catalina usb but even after many tries i wont be able to boot into usb. My spec are same like you except gpu.

Please also tell me about your bios settings

**Comment by tagyro** [comment]
I had the same settings as here @SchmockLord on [his repo](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/blob/master/bios-settings.md) 
What GPU are you using? Nvidia is not supported and AMD only up to RDNA1 in Catalina.
Also, any specific error? My OC is the "debug" version and logs are saved - have you had a look on the EFI partition is any log is saved?
